/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Banco.BuscarDados;
import Classes.Emprestimo;
import Banco.BuscarDevolucao;
import Banco.BusqueiDados;
import Banco.ExcluirEmp;
import Banco.SalvarDevolucao;
import Banco.SalvarEmprestimo;
import Classes.ControleDeAcesso;
import javax.swing.JOptionPane;
import Classes.Devolucao;
import Classes.NovoCliente;


/**
 *
 * @author Familia Peçanha
 */
public class DevolucaoLivroGUI extends javax.swing.JFrame {
 Emprestimo objEmp;
 Devolucao objDev;
 NovoCliente obj;
 ControleDeAcesso OBJ;
    
    /**
     * Creates new form TalvesDevolucao
     */
    public DevolucaoLivroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        statusdevolucao = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        talvezdevolucao = new javax.swing.JFormattedTextField();
        vencimento = new javax.swing.JFormattedTextField();
        Limpar = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        NovaDevolucao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        codigolivro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cpffuncionario = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        statusemprestimo = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        dataemprestimo = new javax.swing.JFormattedTextField();
        datadadevolucao = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        classificacao = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomecompleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        codigoemprestimo = new javax.swing.JTextField();
        pesquisarlivro2 = new javax.swing.JButton();
        cpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Devolução");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        voltar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel6.add(voltar);
        voltar.setBounds(1030, 610, 80, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Devolução", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        jPanel5.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Status da Devolução");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(880, 30, 170, 22);

        statusdevolucao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        statusdevolucao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Selecione o Status da Devolução --", "Realizada", "Realizada com pendencia ", "Não realizada" }));
        statusdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusdevolucaoActionPerformed(evt);
            }
        });
        jPanel5.add(statusdevolucao);
        statusdevolucao.setBounds(820, 60, 310, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Multa em caso de atraso R$");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(890, -30, 210, 22);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Vencimento");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(570, 30, 160, 22);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Data Devolução");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(200, 30, 170, 22);

        try {
            talvezdevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(talvezdevolucao);
        talvezdevolucao.setBounds(200, 60, 130, 30);

        try {
            vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(vencimento);
        vencimento.setBounds(570, 60, 120, 30);

        jPanel6.add(jPanel5);
        jPanel5.setBounds(20, 460, 1180, 110);

        Limpar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPanel6.add(Limpar);
        Limpar.setBounds(370, 610, 110, 31);

        Salvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Salvar.setText("Confirmar Devolução");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        jPanel6.add(Salvar);
        Salvar.setBounds(650, 610, 220, 30);

        NovaDevolucao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NovaDevolucao.setText("Nova Devolução");
        NovaDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaDevolucaoActionPerformed(evt);
            }
        });
        jPanel6.add(NovaDevolucao);
        NovaDevolucao.setBounds(40, 610, 180, 31);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Código ");

        codigolivro.setEditable(false);
        codigolivro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Titulo");

        titulo.setEditable(false);
        titulo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("CPF do Funcinário");

        cpffuncionario.setEditable(false);
        try {
            cpffuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpffuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpffuncionarioActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("Funcionário");

        funcionario.setEditable(false);
        funcionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("Status do Emprestimo");

        statusemprestimo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        statusemprestimo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Selecione um Status --", "Autorizado" }));
        statusemprestimo.setEnabled(false);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Data do Empréstimo");

        dataemprestimo.setEditable(false);
        try {
            dataemprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        datadadevolucao.setEditable(false);
        try {
            datadadevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Data da devolução");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Classificação");

        classificacao.setEditable(false);
        classificacao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("CPF do Cliente ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nome Completo");

        nomecompleto.setEditable(false);
        nomecompleto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Código ");

        codigoemprestimo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pesquisarlivro2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pesquisarlivro2.setText("Pesquisar empréstimo");
        pesquisarlivro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarlivro2ActionPerformed(evt);
            }
        });

        cpf.setEditable(false);
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(codigoemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisarlivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(124, 124, 124)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datadadevolucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(547, 547, 547)
                                .addComponent(jLabel1)))
                        .addContainerGap(421, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigolivro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel24)
                                        .addComponent(cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(cpffuncionario))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(311, 311, 311))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarlivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigolivro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(8, 8, 8)
                        .addComponent(cpffuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(datadadevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2);
        jPanel2.setBounds(10, 10, 1180, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaPrincipalGUI tela = new TelaPrincipalGUI();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void statusdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusdevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusdevolucaoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
if (ValidarDevolucao()){
    try{
        if(PreencherObjDev()){
            SalvarDevolucao INSERIR = new SalvarDevolucao();
            INSERIR.SalvDev(objDev);
            JOptionPane.showMessageDialog(null, "Devolução realizada com sucesso!");
        }
    }catch (Exception Erro) {
                JOptionPane.showMessageDialog(null, "Sua devolução não foi realizada" + Erro);
                    Limpar();

}
}
Limpar();
    }//GEN-LAST:event_SalvarActionPerformed

    private void pesquisarlivro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarlivro2ActionPerformed
 if (ValidarExcluirEmpD()){ 
     try{
         if (PreencherobjEmpD()){
             //SalvarEmprestimo busc = new SalvarEmprestimo();
             //codigoemprestimo.setText(objEmp.getcodigoemprestimo());
             ExcluirEmp pesquisar = new ExcluirEmp();
             objEmp.setCodigoemprestimo(codigoemprestimo.getText());
             objEmp = pesquisar.PesquisarExcluirEmp(codigoemprestimo.getText());
                    if(objEmp == null){
                        JOptionPane.showMessageDialog(null, "Por favor, digite um código válido");
                    }else{                        
                        codigoemprestimo.setText(objEmp.getCodigoemprestimo());
                        codigolivro.setText(objEmp.getCodigolivro());
                        titulo.setText(objEmp.getTitulo());
                        classificacao.setText(objEmp.getClassificacao());          
                        cpffuncionario.setText(objEmp.getCpffuncionario());
                        funcionario.setText(objEmp.getFuncionario());
                        cpf.setText(objEmp.getCpf());
                        nomecompleto.setText(objEmp.getNomecompleto());
                        statusemprestimo.setSelectedIndex(objEmp.getStatusemprestimo());
                        dataemprestimo.setText(objEmp.getDataemprestimo());
                        datadadevolucao.setText(objEmp.getDatadadevolucao());
             }       
             }
         }catch (Exception Erro){
                JOptionPane.showMessageDialog(null, "Erro na conexão!" + Erro);
            }
 
 
 }
 
    }//GEN-LAST:event_pesquisarlivro2ActionPerformed

    private void NovaDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaDevolucaoActionPerformed
        Limpar();
        codigoemprestimo.requestFocus();
        codigolivro.setEditable(true);
        classificacao.setEditable(true);
        titulo.setEditable(true);
        cpffuncionario.setEditable(true);
        funcionario.setEditable(true);
        cpf.setEditable(true);
        nomecompleto.setEditable(true);
        statusemprestimo.setEnabled(true);
        dataemprestimo.setEditable(true);
        datadadevolucao.setEditable(true);
        talvezdevolucao.setEditable(true);
        vencimento.setEditable(true);
        statusdevolucao.setEditable(true);
           // TODO add your handling code here:
    }//GEN-LAST:event_NovaDevolucaoActionPerformed

    private void cpffuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpffuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpffuncionarioActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
    Limpar();
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolucaoLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolucaoLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolucaoLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolucaoLivroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolucaoLivroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JButton NovaDevolucao;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField classificacao;
    private javax.swing.JTextField codigoemprestimo;
    private javax.swing.JTextField codigolivro;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JFormattedTextField cpffuncionario;
    private javax.swing.JFormattedTextField datadadevolucao;
    private javax.swing.JFormattedTextField dataemprestimo;
    private javax.swing.JTextField funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nomecompleto;
    private javax.swing.JButton pesquisarlivro2;
    private javax.swing.JComboBox statusdevolucao;
    private javax.swing.JComboBox statusemprestimo;
    private javax.swing.JFormattedTextField talvezdevolucao;
    private javax.swing.JTextField titulo;
    private javax.swing.JFormattedTextField vencimento;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
private void Limpar(){
    codigoemprestimo.setText("");
        codigolivro.setText("");
        nomecompleto.setText("");
        funcionario.setText("");
        classificacao.setText("");
        titulo.setText("");
        cpffuncionario.setText("");
        cpf.setText("");
        nomecompleto.setText("");
        statusemprestimo.setSelectedIndex(0);
        dataemprestimo.setText("");
        datadadevolucao.setText("");
        talvezdevolucao.setText("");
        vencimento.setText("");
        statusdevolucao.setSelectedIndex(0);
}

    private boolean ValidarExcluirEmpD() {
        if (codigoemprestimo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o codigo do emprestimo");
            codigoemprestimo.requestFocus();
            return false;
        }
        return true;
    }
 private boolean PreencherobjEmpD() {
        objEmp = new Emprestimo();
        objEmp.setCodigoemprestimo(codigoemprestimo.getText());
        return true;
    }

    private boolean PreencherObjDev() {
        objDev = new Devolucao();
        objDev.setCodigoemprestimo(codigoemprestimo.getText());
        objDev.setCodigolivro(codigolivro.getText());
        objDev.setTitulo(titulo.getText());
        objDev.setClassificacao(classificacao.getText());
        objDev.setCpffuncionario(cpffuncionario.getText());
        objDev.setFuncionario(funcionario.getText());
        objDev.setCpf(cpf.getText());
        objDev.setNomecompleto(nomecompleto.getText());
        objDev.setStatusemprestimo(statusemprestimo.getSelectedIndex());
        objDev.setDataemprestimo(dataemprestimo.getText());
        objDev.setDatadadevolucao(datadadevolucao.getText());
        objDev.setTalvezdevolucao(talvezdevolucao.getText());
        objDev.setVencimento(vencimento.getText());
        objDev.setStatusdevolucao(statusdevolucao.getSelectedIndex());
                
        return true;
    
    
    }

    private boolean ValidarDevolucao() {
  if (codigoemprestimo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o codigo do emprestimo!");
            codigoemprestimo.requestFocus();
            return false;
        }
       if (talvezdevolucao.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Digite a data da devolução!");
           talvezdevolucao.requestFocus();
           return false;
        }          
       if (vencimento.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Digite a data do Vencimento!");
           vencimento.requestFocus();
           return false;
       }
      if(statusdevolucao.getSelectedIndex() == (0)){
            JOptionPane.showMessageDialog(null, "Selecione o status");
            statusdevolucao.requestFocus();
            return false;         
       }       
        return true; 
    }
    
    private boolean ValidarExcluir(){
    
        if (cpf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Informe o cpf do cliente");
            cpf.requestFocus();
            return false;
        }
        return true;
    }
    private boolean ValidarExcluirControle(){
        
        if(cpffuncionario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Informe o cpf do funcionário");
            cpffuncionario.requestFocus();
            return false;
        }
        return true;
    }
    private boolean PreencherObjExcluir() throws Exception {
        obj = new NovoCliente ();
        obj.setCpf(cpf.getText());
        return true;
    }
    
    private boolean PreencherOBJExcluirControle() throws Exception{
        OBJ = new ControleDeAcesso ();
        OBJ.setCpffuncionario(cpffuncionario.getText());
        return true;
    }
}


   






